Feature/issue191 wipp library refactor
PolusAI/WIPP-frontend pull request #3
Opened 2020-11-30 15:30 UTC by kannabhargav

## What does this PR do?

## Related issues

2020-12-02 21:43 UTC, sunnielyu requested changes
Can we separate the ingress from the service?

2020-12-04 18:40 UTC, mapleknight requested changes
Please split ingress from other application resources.

2020-12-04 20:57 UTC, mapleknight requested changes
you don't need to add services.yaml in prod deployment folder.

2020-12-07 15:19 UTC, mapleknight requested changes

2020-12-07 15:19 UTC, mapleknight commented on deploy.sh
> +kubectl apply --kubeconfig=${KUBECONFIG} -f deploy/kubernetes/frontend-deployment.yaml
Please change the apply sequence.

2020-12-07 16:03 UTC, kannabhargav commented on deploy.sh
> +kubectl apply --kubeconfig=${KUBECONFIG} -f deploy/kubernetes/frontend-deployment.yaml
updated the sequence

2020-12-07 17:52 UTC, sunnielyu approved these changes

2020-12-07 17:53 UTC, merged