Feature/issue191 wipp library refactor angular upgrade
PolusAI/WIPP-frontend pull request #4
Opened 2021-02-09 01:34 UTC by mohamedOuladi

## What does this PR do?

- Refactored the routing in the library: instead of using hard coded paths in components, the paths are now injected into the library from the env file
- Upgraded angular version from 7 to 9: upgraded other 3rd party libraries as well to work properly with angular 9
- Added Generic Data upload feature

## Related issues

#191 https://github.com/usnistgov/WIPP-frontend/issues/191
#192 https://github.com/usnistgov/WIPP-frontend/issues/192
#184 https://github.com/usnistgov/WIPP-frontend/issues/184

2021-02-09 01:39 UTC, mohamedOuladi commented
I disabled inline editor library because it's causing issues with angular 9. We might need to look into an alternative solution to give the user the ability to modify collections' names.

2021-02-09 17:15 UTC, sunnielyu requested changes

2021-02-09 17:15 UTC, sunnielyu commented on deploy/docker/VERSION
> +3.1.3
I would bump the minor version. The patch version should be reserved for bug fixes.

2021-02-09 17:15 UTC, sunnielyu commented on projects/wipp-frontend-lib/src/lib/generic-data/generic-data-detail/generic-data-detail.component.ts
> +// @NgModule({
This module block can be removed

2021-02-09 17:15 UTC, sunnielyu commented on projects/wipp-frontend-lib/src/lib/generic-data/generic-data-detail/generic-data-detail.component.ts
> +import {NgbModal, NgbModule} from '@ng-bootstrap/ng-bootstrap';
NgbModule import can be removed

2021-02-09 17:15 UTC, sunnielyu commented on projects/wipp-frontend-lib/src/lib/generic-data/generic-data-detail/generic-data-detail.component.ts
> +import { AfterViewInit, Component, ElementRef, NgModule, OnInit, ViewChild } from '@angular/core';
NgModule import can be removed

2021-02-09 17:15 UTC, sunnielyu commented on projects/wipp-frontend-lib/src/lib/generic-data/generic-data-detail/generic-data-detail.component.ts
> +import {BytesPipe, NgMathPipesModule} from 'angular-pipes';
NgMathPipesModule can be removed

2021-02-09 17:15 UTC, sunnielyu commented on projects/wipp-frontend-lib/src/lib/generic-data/generic-data-detail/generic-data-detail.component.ts
> +      console.log(file, event);
Remove console.log

2021-02-09 17:15 UTC, sunnielyu commented on projects/wipp-frontend-lib/src/lib/generic-data/generic-data-new/generic-data-new.component.ts
> +    console.log('createCollection');
Remove console.log

2021-02-09 17:15 UTC, sunnielyu commented on projects/wipp-frontend-lib/src/lib/stitching-vector/stitching-vector-detail/stitching-vector-detail.component.ts
> +    console.log('hello');
Remove console.log

2021-02-09 17:15 UTC, sunnielyu commented on projects/wipp-frontend-lib/src/lib/dynamic-content/dynamic-content.component.ts
> +  'notabook': NotebookTemplateComponent,
typo

2021-02-09 17:15 UTC, sunnielyu commented on projects/wipp-frontend-lib/src/lib/dynamic-content/dynamic-content.component.ts
> +    var factoryClass;
Use `let` instead of `var

2021-02-09 21:13 UTC, mohamedOuladi commented on deploy/docker/VERSION
> +3.1.3
fixed

2021-02-09 21:14 UTC, mohamedOuladi commented on projects/wipp-frontend-lib/src/lib/generic-data/generic-data-detail/generic-data-detail.component.ts
> +// @NgModule({
fixed

2021-02-11 14:48 UTC, sunnielyu approved these changes

2021-02-11 14:49 UTC, merged